[server]
headless = true
enableCORS = true
enableXsrfProtection = true
port = 8501

[theme]
base = "light"
primaryColor = "#0F766E"
secondaryBackgroundColor = "#F2F5F7"
textColor = "#0F172A"
font = "sans serif"
